
// List of products to be displayed

products = [
    {
        id: 1001,
        name: "Maths",
        location: "London",
        price: 50,
        image: "Images/math.png",
        spaces: 5,
    },
    {
        id: 1002,
        name: "English",
        location: "Brimingham",
        price: 40,
        image: "Images/english.png",
        spaces: 5,
    },
    {
        id: 1003,
        name: "Physics",
        location: "York",
        price: 45,
        image: "Images/science.jpeg",
        spaces: 5,
    },
    {
        id: 1004,
        name: "Chemistry",
        location: "Cambridge",
        price: 50,
        image: "Images/CHEMISTRY.jpg",
        spaces: 5,
    },
    {
        id: 1005,
        name: "Medicine",
        location: "Oxford",
        price: 45,
        image: "Images/MEDICINE.jpg",
        spaces: 5,
    },
    {
        id: 1006,
        name: "Geography",
        location: "Northampton",
        price: 50,
        image: "Images/geography.jpeg",
        spaces: 5,
    },
    {
        id: 1007,
        name: "Statistics",
        location: "Brent Cross",
        price: 50,
        image: "Images/math.png",
        spaces: 5,
    },
    {
        id: 1008,
        name: "IT",
        location: "Hendon",
        price: 40,
        image: "Images/IT.png",
        spaces: 5,
    },
    {
        id: 1009,
        name: "History",
        location: "Milton Keynes",
        price: 40,
        image: "Images/history.jpeg",
        spaces: 5,
    },
    {
        id: 1010,
        name: "Biology",
        location: "Hereford",
        price: 45,
        image: "Images/BIOLOGY.jpg",
        spaces: 5,
    }
]